# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- group: ConnectDb
- name: tag
  value: '0.0.$(Build.BuildId)'


stages: 
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: replacetokens@5
      inputs:
        rootDirectory: '$(Build.sourcesdirectory)/producto-service/src/main/resources/'
        targetFiles: '**/*.properties'
        encoding: 'auto'
        tokenPattern: 'rm'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true
    - task: Gradle@2
      displayName: 'gradlew build'
      inputs:
        gradleWrapperFile: '$(Parameters.wrapperScript)'
        tasks: '$(Parameters.tasks)'
        workingDirectory: '$(Build.sourcesdirectory)/producto-service'
    - task: Docker@2
      displayName: Build and Push
      inputs:
        containerRegistry: 'MyConnect'
        repository: 'camilolagos/producto-service'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'