# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- group: ConnectDb
- name: tag
  value: '0.0.$(Build.BuildId)'


stages: 
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: replacetokens@5
      inputs:
        rootDirectory: '$(Build.sourcesdirectory)/cliente-service'
        targetFiles: '**/*.properties'
        encoding: 'auto'
        tokenPattern: 'rm'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true

    - bash: |
        chmod +x $(Build.sourcesdirectory)/cliente-service/gradlew
        $(Build.sourcesdirectory)/cliente-service/gradlew bootJar
      displayName: Build